-- =====================================================
-- COMPETENCY SYSTEM MIGRATION V2 (Partial Update)
-- =====================================================
-- Deskripsi: File ini hanya memperbarui tabel transactional (mapping/history), 
-- view, dan function, tanpa menyentuh master data (competency/position).

-- 1. Drop View terlebih dahulu karena view tergantung pada kolom yang akan diubah
DROP VIEW IF EXISTS v_competency_status;

-- =====================================================
-- 2. UPDATE TABLE STRUCTURES (Idempotent)
-- =====================================================

-- [Table: competency_mapping]
CREATE TABLE IF NOT EXISTS competency_mapping (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nrp text not null,
  competency_id bigint not null,
  obtained_date date,
  expired_date date,
  active boolean default true,
  
  -- Constraint (akan error jika manpower/competency belum ada, tapi asumsi user sudah ada)
  constraint fk_mapping_manpower foreign key (nrp) references manpower(nrp) on delete cascade,
  constraint fk_mapping_competency foreign key (competency_id) references competency(id) on delete cascade,
  constraint unique_manpower_competency unique (nrp, competency_id)
);

-- Add 'document_url' column if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'competency_mapping' AND column_name = 'document_url') THEN
    ALTER TABLE competency_mapping ADD COLUMN document_url text;
  END IF;
END $$;

-- Add 'latest_history_id' column if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'competency_mapping' AND column_name = 'latest_history_id') THEN
    ALTER TABLE competency_mapping ADD COLUMN latest_history_id bigint;
  END IF;
END $$;


-- [Table: competency_history]
CREATE TABLE IF NOT EXISTS competency_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  nrp text not null,
  competency_id bigint not null,
  training_date date not null,
  expired_date date,
  training_type text default 'renewal',
  note text,
  
  constraint fk_hist_manpower foreign key (nrp) references manpower(nrp) on delete cascade,
  constraint fk_hist_competency foreign key (competency_id) references competency(id) on delete cascade
);

-- Add 'document_url' column to history if not exists
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'competency_history' AND column_name = 'document_url') THEN
    ALTER TABLE competency_history ADD COLUMN document_url text;
  END IF;
END $$;

-- Add Circular Foreign Key (Mapping -> History)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'fk_mapping_history') THEN
    ALTER TABLE competency_mapping 
    ADD CONSTRAINT fk_mapping_history 
    FOREIGN KEY (latest_history_id) REFERENCES competency_history(id) ON DELETE SET NULL;
  END IF;
END $$;


-- =====================================================
-- 3. UPDATE FUNCTIONS & TRIGGERS
-- =====================================================

-- Function: fn_after_training_insert
CREATE OR REPLACE FUNCTION fn_after_training_insert()
RETURNS trigger
LANGUAGE plpgsql
AS $$
DECLARE
  v_days smallint;
  v_expired date;
BEGIN

  -- Ambil durasi berlaku dari master competency
  SELECT days_active
  INTO v_days
  FROM competency
  WHERE id = NEW.competency_id;

  -- Hitung expired date jika tidak disediakan
  IF NEW.expired_date IS NULL AND v_days IS NOT NULL THEN
    v_expired := NEW.training_date + v_days;
  ELSE
    v_expired := NEW.expired_date;
  END IF;

  -- Insert atau Update ke Mapping
  INSERT INTO competency_mapping (
    nrp,
    competency_id,
    obtained_date,
    expired_date,
    active,
    document_url,
    latest_history_id
  )
  VALUES (
    NEW.nrp,
    NEW.competency_id,
    NEW.training_date,
    v_expired,
    true,
    NEW.document_url,
    NEW.id
  )
  ON CONFLICT (nrp, competency_id)
  DO UPDATE SET
    obtained_date = EXCLUDED.obtained_date,
    expired_date = EXCLUDED.expired_date,
    active = true,
    document_url = EXCLUDED.document_url,
    latest_history_id = EXCLUDED.latest_history_id;

  RETURN NEW;
END;
$$;

-- Trigger: Recreate logic
DROP TRIGGER IF EXISTS trg_training_insert ON competency_history;

CREATE TRIGGER trg_training_insert
AFTER INSERT ON competency_history
FOR EACH ROW
EXECUTE FUNCTION fn_after_training_insert();


-- Function: refresh_competency_expired
CREATE OR REPLACE FUNCTION refresh_competency_expired()
RETURNS void
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE competency_mapping
  SET active = false
  WHERE expired_date < current_date;
END;
$$;


-- =====================================================
-- 4. RECREATE VIEW
-- =====================================================
CREATE OR REPLACE VIEW v_competency_status AS
SELECT
  cm.latest_history_id AS id, -- Menggunakan ID History agar bisa diedit/hapus record aslinya
  cm.nrp,
  mp.nama,
  cm.competency_id,
  c.competency_name,
  cm.obtained_date,
  cm.expired_date,
  cm.active,
  cm.document_url,
  CASE
    WHEN cm.expired_date < current_date THEN 'expired'
    WHEN cm.expired_date <= current_date + 30 THEN 'soon_expired'
    ELSE 'valid'
  END AS status
FROM competency_mapping cm
JOIN manpower mp ON mp.nrp = cm.nrp
JOIN competency c ON c.id = cm.competency_id;


-- =====================================================
-- 5. POLICIES & PERMISSIONS
-- =====================================================

-- Ensure RLS Enabled
ALTER TABLE competency_mapping ENABLE ROW LEVEL SECURITY;
ALTER TABLE competency_history ENABLE ROW LEVEL SECURITY;

-- Helper Block to safest create policies
DO $$
BEGIN
  -- Mapping Policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'read mapping' AND tablename = 'competency_mapping') THEN
    CREATE POLICY "read mapping" ON competency_mapping FOR SELECT TO authenticated USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service full mapping' AND tablename = 'competency_mapping') THEN
    CREATE POLICY "service full mapping" ON competency_mapping FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;

  -- History Policies
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'read history' AND tablename = 'competency_history') THEN
    CREATE POLICY "read history" ON competency_history FOR SELECT TO authenticated USING (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'insert training' AND tablename = 'competency_history') THEN
    CREATE POLICY "insert training" ON competency_history FOR INSERT TO authenticated WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'service full history' AND tablename = 'competency_history') THEN
    CREATE POLICY "service full history" ON competency_history FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow view' AND tablename = 'competency_history') THEN
    CREATE POLICY "Allow view" ON competency_history FOR SELECT TO authenticated USING (true);
  END IF;
END $$;

-- Grant RPC
GRANT EXECUTE ON FUNCTION refresh_competency_expired() TO service_role;
