create table public.loto_sessions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  create_shift smallint null,
  fuelman text null,
  operator text null,
  warehouse_code text null,
  session_code text not null,
  constraint loto_sessions_pkey primary key (id, session_code),
  constraint loto_sessions_session_code_key unique (session_code),
  constraint loto_sessions_fuelman_fkey foreign KEY (fuelman) references manpower (nrp) on update CASCADE,
  constraint loto_sessions_operator_fkey foreign KEY (operator) references manpower (nrp) on update CASCADE,
  constraint loto_sessions_warehouse_code_fkey foreign KEY (warehouse_code) references storage (warehouse_id)
) TABLESPACE pg_default;