-- Create Order Status Enum
DO $$ BEGIN
    CREATE TYPE order_status AS ENUM (
        'WAITING APPROVAL MR',
        'WAITING PR NUMBER',
        'WAITING APPROVAL PR',
        'WAITING RESERVATION',
        'WAITING APPROVAL RESERVATION',
        'CLOSED'
    );
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create Materials Table
CREATE TABLE IF NOT EXISTS public.materials (
  id bigint generated by default as identity not null,
  material_code text not null,
  item_description text null,
  mnemonic text null,
  material_group text null,
  population text null,
  item_name text null,
  material_priority smallint null,
  stock_taking_order smallint null,
  colloquials text null,
  physical_url text null,
  constraint materials_pkey primary key (id, material_code),
  constraint materials_material_code_key unique (material_code)
) TABLESPACE pg_default;

-- Create Orders Table (Header)
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  pr_number text null,
  order_date date null,
  po_number text null,
  creator text null,
  status text null,
  stocked_item boolean null,
  supply_to text null,
  reservation_number text null,
  constraint orders_pkey primary key (id),
  constraint orders_supply_to_fkey foreign KEY (supply_to) references manpower (nrp)
) TABLESPACE pg_default;

-- Add order_date column if it doesn't exist (for existing tables)
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'orders' AND column_name = 'order_date') THEN
        ALTER TABLE public.orders ADD COLUMN order_date DATE DEFAULT CURRENT_DATE;
    END IF;
END $$;

-- Create Orders Item Table (Detail)
CREATE TABLE IF NOT EXISTS public.orders_item (
  id uuid not null default gen_random_uuid (),
  mr_number integer null,
  material_code text null,
  item_description text null,
  qty_orders numeric null default 0,
  qty_received numeric null default 0,
  item_no integer null,
  created_at timestamp with time zone null default now(),
  constraint orders_item_pkey primary key (id),
  constraint orders_item_material_code_fkey foreign KEY (material_code) references materials (material_code),
  constraint orders_item_mr_number_fkey foreign KEY (mr_number) references orders (id) on delete CASCADE
) TABLESPACE pg_default;

-- RLS Policies

-- Materials
ALTER TABLE public.materials ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.materials FOR SELECT USING (true);
-- Assuming materials are mastered by admins, insert/update restricted? For now allow auth.
CREATE POLICY "Enable write for authenticated" ON public.materials FOR ALL USING (auth.role() = 'authenticated');

-- Orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.orders FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.orders FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users" ON public.orders FOR UPDATE USING (auth.role() = 'authenticated');

-- Orders Item
ALTER TABLE public.orders_item ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for all users" ON public.orders_item FOR SELECT USING (true);
CREATE POLICY "Enable insert for authenticated users" ON public.orders_item FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Enable update for authenticated users" ON public.orders_item FOR UPDATE USING (auth.role() = 'authenticated');
